In [2]:
import sys
from pathlib import Path
# sys.path.insert(0,str(Path(r'C:\Users\ku51015\CHMURA\mystuff\Graph-Vizualisation-Rating-Metric-randoms').resolve()))
sys.path.insert(0,str(Path(r'C:\Users\Kinga\Desktop\MAGISTERKA\Graph-Vizualisation-Rating-Metric-3').resolve()))

from graph_generating_script import *
from graph_metric_script import *
import matplotlib.pyplot as plt
import igraph as ig
import numpy as np
import pickle
import os
# List of layouts
np.random.seed(212)

# Reading lambdas from corr

In [3]:
BA_corr = pd.read_csv(r'lambdas\BA_corrs.csv')
BA_corr.head()

,score,node_distribution,node_distribution_raw,distance_to_borderlines,distance_to_borderlines_raw,edge_length_sum,edge_length_sum_raw,edge_node_distance_contribution,edge_node_distance_contribution_raw,count_edge_crossings,count_edge_crossings_raw,communities_closeness,sum_of_angles,symmetry,category
0,1.0,-0.438908,-0.295487,0.493136,0.513931,0.188714,0.152569,-0.0563,-0.230325,-0.065893,-0.138188,0.295741,0.054358,-0.514301,BA

In [4]:
BA_corr.iloc[:, :-1] = BA_corr.iloc[:, :-1].applymap(lambda x: 0 if abs(x) < 0.2 else x)
BA_corr.head()

,score,node_distribution,node_distribution_raw,distance_to_borderlines,distance_to_borderlines_raw,edge_length_sum,edge_length_sum_raw,edge_node_distance_contribution,edge_node_distance_contribution_raw,count_edge_crossings,count_edge_crossings_raw,communities_closeness,sum_of_angles,symmetry,category
0,1.0,-0.438908,-0.295487,0.493136,0.513931,0.0,0.0,0.0,-0.230325,0.0,0.0,0.295741,0.0,-0.514301,BA

In [6]:
# From abservation above
BA_corr.drop(columns=['node_distribution_raw', 'distance_to_borderlines', 'edge_length_sum_raw', 'edge_node_distance_contribution',
                      'count_edge_crossings_raw'], inplace=True, axis=1)

BA_corr.head()

,score,node_distribution,distance_to_borderlines_raw,edge_length_sum,edge_node_distance_contribution_raw,count_edge_crossings,communities_closeness,sum_of_angles,symmetry,category
0,1.0,-0.438908,0.513931,0.0,-0.230325,0.0,0.295741,0.0,-0.514301,BA

In [30]:
def calculate_metric(lambdas, G, posdf):

    values = [
        node_distribution_raw(posdf),
        distance_to_borderlines_raw(posdf),
        edge_length_sum(G, posdf),
        edge_node_distance_contribution_raw(G, posdf)[0],
        count_edge_crossings(G, posdf),
        measure_communities_closeness(G, posdf),
        sum_of_angles(G, posdf),
        measure_graph_symmetry(G, posdf)
    ]

    i=0
    score=0
    for col in lambdas.columns:
        if col not in ['score', 'category']:

            component = lambdas[col][0] * values[i]
            print(f'{col} : {round(component, 2)}')
            score += component
            i+=1
        
    # score = -0.42*node_distribution_raw(posdf) +0.34*edge_length_sum(G, posdf) + 0.39*measure_communities_closeness(G, posdf) -0.47*measure_graph_symmetry(G, posdf)
    # score = -0.42*rescaled_values[0] +0.34*rescaled_values[1] + 0.39*rescaled_values[2] -0.47*rescaled_values[3]

    print(f'Score: {round(score, 2)}')
    return score

# Tests

In [8]:
with open(r'tests\graph_objects\graph_ER_1_kamada_kawai.pkl', 'rb') as f:
    G = pickle.load(f)
posdf = pd.read_csv(r'tests\pos_dfs\posdf_ER_1_kamada_kawai.csv')

In [33]:
# nx.draw(G, pos=posdf)
calculate_metric(BA_corr, G, posdf)

node_distribution : -6.14
distance_to_borderlines_raw : 60.68
edge_length_sum : 0.0
edge_node_distance_contribution_raw : -8.44
count_edge_crossings : 0.0
communities_closeness : 0.01
sum_of_angles : 0.0
symmetry : -0.49
Score: 45.62

45.61998396584576

In [35]:
posdf_worse = pd.read_csv(r'tests\pos_dfs\posdfworse_ER_1_kamada_kawai.csv')
calculate_metric(BA_corr, G, posdf_worse)

node_distribution : -11.63
distance_to_borderlines_raw : 8.62
edge_length_sum : 0.0
edge_node_distance_contribution_raw : -36.96
count_edge_crossings : 0.0
communities_closeness : 0.02
sum_of_angles : 0.0
symmetry : -0.48
Score: -40.42

-40.42348180746158

# test2

In [36]:
with open(r'tests\graph_objects\graph_ER_2_kamada_kawai.pkl', 'rb') as f:
    G = pickle.load(f)
posdf = pd.read_csv(r'tests\pos_dfs\posdf_ER_2_kamada_kawai.csv')

In [37]:
# nx.draw(G, pos=posdf)
calculate_metric(BA_corr, G, posdf)

node_distribution : -14.91
distance_to_borderlines_raw : 62.42
edge_length_sum : 0.0
edge_node_distance_contribution_raw : -11.96
count_edge_crossings : 0.0
communities_closeness : 0.02
sum_of_angles : 0.0
symmetry : -0.47
Score: 35.09

35.09288483432697

In [38]:
posdf_worse = pd.read_csv(r'tests\pos_dfs\posdfworse_ER_2_kamada_kawai.csv')
calculate_metric(BA_corr, G, posdf_worse)

node_distribution : -15.62
distance_to_borderlines_raw : 62.85
edge_length_sum : 0.0
edge_node_distance_contribution_raw : -31.52
count_edge_crossings : 0.0
communities_closeness : -0.05
sum_of_angles : 0.0
symmetry : -0.46
Score: 15.2

15.196766390707733